#!/usr/bin/python

# our exception class --- track a general and detailed error message

# track the detailed part of the last error generated by a subsystem here
# we present it with a summary during error messages
last_detail = ""

class Error(Exception):

    def __init__(self, message, detail=None):
        global last_detail

        self.message = message
        if detail:
            self.detail = detail
            last_detail = detail
        else:
            self.detail = last_detail

        logging.debug('lights: Error %s %s', self.message, self.detail)

    def __str__(self):
        return '%s - %s' % (self.message, self.detail)

